### ISSUE TITLE
Player could not enter level 4

### ISSUE THREAD

**Issue by HanJiang915** [tonikolaba/BatBat-Game#2]
Hi 
  I meet a problem like this, I can run the game and enter the options or quit. But I can not enter level 4 after I play level3 . It will show this information. 
Exception in thread "Thread-0" java.lang.NullPointerException
	at al.artofsoul.batbatgame.gamestate.GameState.update(GameState.java:245)
	at al.artofsoul.batbatgame.gamestate.Level4State.update(Level4State.java:69)
	at al.artofsoul.batbatgame.gamestate.GameStateManager.update(GameStateManager.java:76)
	at al.artofsoul.batbatgame.main.GamePanel.update(GamePanel.java:104)
	at al.artofsoul.batbatgame.main.GamePanel.run(GamePanel.java:83)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by baixi-cs** [comment]
I saw it

**Comment by tonikolaba** [comment]
@HanJiang915 & @baixi-cs Now it's fixed, thanks :information_desk_person:. :100: :white_check_mark: :ok_hand:  :thumbsup:
